use lib qw(lib);
use Test::More;
plan tests => 10;
use_ok('JRobin');
use_ok('JRobin::Archive');
use_ok('JRobin::ArcState');
use_ok('JRobin::Constants');
use_ok('JRobin::Datasource');
use_ok('JRobin::Double');
use_ok('JRobin::Header');
use_ok('JRobin::Robins');
use_ok('JRobin::String');
use_ok('JRobin::Unpack');
