use lib qw(lib);
use Test::More;
plan tests => 8;
use_ok('JRobin');
use_ok('JRobin::Archive');
use_ok('JRobin::ArcState');
use_ok('JRobin::Constants');
use_ok('JRobin::Datasource');
use_ok('JRobin::Header');
use_ok('JRobin::Robins');
use_ok('JRobin::Utils');
